//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFC_Toolbox.v._4._0.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sqlserver")]
        public string DbType {
            get {
                return ((string)(this["DbType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=RDPFC-POSCOORD\\SQLEXPRESS;Database=PFCToolbox;User Id=pfctoolbox;\r\nPasswor" +
            "d=pfctoolbox;")]
        public string DbConnection1 {
            get {
                return ((string)(this["DbConnection1"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=192.168.0.29\\SQLEXPRESS;Database=STORESQL;User Id=ncbp;\r\nPasswor" +
            "d=289iwqw;")]
        public string DbConnection2
        {
            get
            {
                return ((string)(this["DbConnection2"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=192.168.0.30\\SQLEXPRESS;Database=STORESQL;User Id=ncbp;\r\nPasswor" +
            "d=289iwqw;")]
        public string DbConnection3
        {
            get
            {
                return ((string)(this["DbConnection3"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=10.190.30.30\\SQLEXPRESS;Database=STORESQL;User Id=ncbp;\r\nPasswor" +
            "d=289iwqw;")]
        public string DbConnection4
        {
            get
            {
                return ((string)(this["DbConnection4"]));
            }
        }
    }
}
